services:
  jjambot:
    image: jjambot:latest
    build: ./
    ports:
      - "38888:80"
    environment:
      # Telegram 토큰
      TELOXIDE_TOKEN:

      # 국방부 API 토큰 
      JJAM_TOKEN:

      # 부대 코드
      UNIT_CODE:
      
    volumes:
      - ./data:/usr/src/myapp/data:jjamdata
    
